# Generated by Django 5.2.3 on 2025-06-30 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0004_genre_book_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.IntegerField(default=1001, primary_key=True, serialize=False),
        ),
    ]
