# Generated by Django 5.2.3 on 2025-06-30 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0007_alter_book_published_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='genres',
        ),
    ]
